### ISSUE TITLE
numpy.ndarray size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by alitekdemir** [blankly-finance/blankly#102]
## Description
I'm trying to work with google colab, but I get the error "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject".

!pip install --upgrade numpy==1.19.2
I tried the numpy version with the above, still didn't work.
But it's very interesting, I got it working yesterday after repeating it a few times.
![colab](https://user-images.githubusercontent.com/1507344/149806402-20cc27ae-1117-4de0-89e8-8f6b5487d88e.png)

## Platform Info
 - Python version: Python 3.7.12
 - Platform: https://colab.research.google.com/

**Additional context**
I'll open a separate thread for windows :(
blankly.utils.exceptions.APIException: Invalid API Key, IP, or permissions for action - are you trying to use your normal exchange keys while in sandbox mode?

**Comment by EmersonDove** [comment]
Interesting, it looks like I've run across this issue before.

Try using the most up to date numpy with `pip install numpy --upgrade`

It might works after reinstalling the package, sometimes that fixes errors with:
`pip uninstall blankly`
`pip install blankly`

**Comment by alitekdemir** [comment]
firstly i run this code
`!pip install --upgrade numpy`
`!pip install --upgrade blankly`

after that just i try this code
`import blankly` and its works on my laptop.
I hope its working on my desktop. I try it tomorrow.
Thank you for your attention.

**Comment by EmersonDove** [comment]
Awesome, keep us updated, I would like to get to the bottom of this reoccurring issue

**Comment by jckbr** [comment]
Ran into this issue on the latest build, 1.18.25b0. Got it working with build 1.16.12b0
