### ISSUE TITLE
Plotted returns and cumulative returns don't match

### ISSUE THREAD

**Issue by sjhermanek** [Blankly-Finance/Blankly#105]
## Description
Returns in `results.metrics["Cumulative Returns (%)"]` don't match charted returns in Bokehplot or `Account Value (USD)` in `Account History`

## Platform Info
 - Using latest blankly package
 - Running backtest over `2d`

**Additional context**
![image](https://user-images.githubusercontent.com/7539457/150352442-6fba2135-87bc-4318-ac23-077edcc647cf.png)
![image](https://user-images.githubusercontent.com/7539457/150352489-dfcb3c08-0f00-42af-899f-e42c05df6ccf.png)
![image](https://user-images.githubusercontent.com/7539457/150352564-a7d8278a-020a-4b22-b74f-7ac5fea69ab8.png)

**Comment by bfan1256** [comment]
Just fixed to make `cum_returns` to use `account_values` instead of `resampled_account_values`, this should fix the cumulative returns
