### ISSUE TITLE
Third party signal support

### ISSUE THREAD

**Issue by doudoujay** [blankly-finance/blankly#109]
## Description of Feature Request
Support third party signal. Currently everything is soley based on market data

## Why is it important?
Adds more variety of trading strategies like integrating with newsfeed, sentiment scores, etc.

## How would you use the feature?
example:
```
add_price_event(data_handler, symbol, ...)
```

## OPTIONAL: How would you implement this?
Give us some of your initial thoughts for implementing this. 

## Would you like to Contribute?

- [ x] Yes, I would love to contribute to this feature request 🎉
- [ ] No, but please keep me posted 🎉

**Additional Information**
Add any other context about the feature request here including what other packages have done, linked issues, and more.

**Comment by EmersonDove** [comment]
This is an awesome idea & we are working on a pretty cool implementation of this in the background. I will loop you in when we open source it because it looks like you might be interested in contributing. You can expect a rollout sometime this spring.

**Comment by doudoujay** [comment]
Happy to contribute!
