### ISSUE TITLE
How to remove a subscribed ticker?

### ISSUE THREAD

**Issue by doudoujay** [blankly-finance/blankly#110]
## Description of Feature Request
We can add listener to a ticker stream via
```
strategy.add_price_event(price_event, symbol='BTC-USD', resolution='1d', init=init)
```
How to remove a subscribed ticker?

## Why is it important?
This would enabled dynamic ticker selection in our strategy

## How would you use the feature?
```
strategy.delete_price_event()
```
or 
```
strategy.all_subscribed_events.delete(id)
```

## OPTIONAL: How would you implement this?
Give us some of your initial thoughts for implementing this. 

## Would you like to Contribute?

- [ x] Yes, I would love to contribute to this feature request 🎉
- [ ] No, but please keep me posted 🎉

**Additional Information**
Add any other context about the feature request here including what other packages have done, linked issues, and more.

**Comment by EmersonDove** [comment]
This is another great idea. It's pretty easy to do on the live trading side, we would just have to generate ID's for each event and associate that with the `Scheduler` class which drives it. When deleting it would just stop (or maybe even just pause) the scheduler.
