### ISSUE TITLE
Code often freezes when paper trading

### ISSUE THREAD

**Issue by Fschoeller** [blankly-finance/blankly#128]
Hi!
Around 50% of the time when starting a bot it will freeze up when using the broker interface  and wait for thread lock. When killing the script i get
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

restarting the script often solves the problem.

**Comment by EmersonDove** [comment]
Interesting error,

Are you running a websocket or running a price event at less than 60 second interval?

**Comment by Fschoeller** [comment]
Do you mean whether `"use_sandbox_websockets": true` ?
I have a two price events. One running on 1m interval and one on 1d interval

**Comment by EmersonDove** [comment]
I'm racking my brain right now trying to figure this one out.

Are you using a `blankly.PaperTrade()` object or just connecting directly to a live sandbox exchange?

**Comment by Fschoeller** [comment]
using `strategy.start()` with `use_sandbox: true`

**Comment by Fschoeller** [comment]
Looks like it might have been a problem on my side. Found i had some nan values from a ticker that yfinance could not find.

**Comment by bfan1256** [comment]
Glad everything was figurd out. @Fschoeller , we'd love to hear more about what you're building and ultimately how we can help (https://calendly.com/blankly) :D

**Comment by bfan1256** [comment]
Love for you to join our discord too :D 
https://discord.gg/xJAjGEAXNS
