### ISSUE TITLE
How to short with Binance ?

### ISSUE THREAD

**Issue by faycal-rakza** [blankly-finance/blankly#129]
Hello,

I didn't find mentions about futures or shorting. Is it possible ?

I tried this 
```code
state.interface.limit_order(symbol, 'sell', price, quantity)
```

```code
blankly.utils.exceptions.InvalidOrder: Not enough base currency. Available: 0.0. hold: 0. requested: 100
```

**Comment by EmersonDove** [comment]
Hey we are working on the binance futures integration right now on #127. It's not in yet but it's coming soon

**Comment by qmatias** [comment]
Like Emerson said we are actively working on this. Out of curiosity what kind of API would you like to see for futures trading?
