### ISSUE TITLE
`cancel_order` does not move value from hold to available

### ISSUE THREAD

**Issue by pushkarmishra** [blankly-finance/blankly#134]
## Description
When using Binance interface in backtesting, calling `cancel_order` on a sell limit order does not move the value of the asset from hold to available.

## settings.json
```json
settings.json here
```

## backtest.json (if applicable)
```json
backtest.json here
```

## Error (if applicable)
```text
Error here
```

## Platform Info
 - Python version:
 - Platform:

**Additional context**

**Comment by EmersonDove** [comment]
Hey thanks for opening an issue, I'll look into this and attach it to a pull.
