### ISSUE TITLE
KeylessExchange does not provide OHLCV data on bar event

### ISSUE THREAD

**Issue by lomagno2003** [blankly-finance/blankly#136]
## Description of Feature Request
First of all, congratz on your work on Blankly. I've also used Freqtrade and Backtrader and even though they provide other capabilities that you don't, you rock on making this framework simple to use.

I'm developing a strategy using Artificial Neural Networks trained using Genetic Algorithms. In here, I need to run multiple back tests in order to calculate the fitness of each individual. For this, I'm using Blankly backtest where I need to initialize an Exchange. I was using Alpaca but during initialization and execution, it performs some HTTPS calls that slows down the training (even if they are just a few). I switched to KeyLess exchange but I noticed that it mocks the OHCLV data ([reference](https://github.com/blankly-finance/blankly/blob/main/blankly/exchanges/interfaces/keyless/keyless_api.py#L58-L77)). 

Would be nice to have this Exchange (or maybe another exchange) to provide all the OHCLV data. Maybe one exchange that requires a directory with multiple CSV files, one per Symbol (maybe similar to the ones generated by the backtests on the price_cache folder).

## Why is it important?
Maybe other people needs this feature to perform offline trainings and backtests using the full OHCLV data. Just as a silly example, I want to code while I'm flying without internet connectivity and be able to tests my strategy which uses volume indicators.

## How would you use the feature?
I would like to provide a folder that will contains all the CSV files that can be consumed by this Exchange. For instance:
```
if __name__ == "__main__":
    exchange = blankly.CSVExchange(folder='price_caches', initial_account_values={'USD': 100000})
    strategy = blankly.Strategy(exchange)
    strategy.add_bar_event(self.bar_event, 'AAPL', resolution='1d', init=self.init)

    strategy.backtest(start_date="20/10/2021", end_date="01/03/2022")

```
In here, the folder might have the following files:
- `AAPL,1614793059,1646329059,86400.csv`
- `TSLA,1634688000,1641168000,1800.csv`

How would you implement this?
As mentioned, I'll probably do something quite similar to the KeylessExchange but instead of providing a file, I'll read each file on a folder looking for CSV files that follows the cached prices format and in their header have the `high,low,volume,close,open,time`. Then I'll somehow do a lazy load of those files (depending the symbols and date range that is needed)

## Would you like to Contribute?

- [x] Yes, I would love to contribute to this feature request 🎉
- [ ] No, but please keep me posted 🎉

**Additional Information**
- Dummy load of OHCLV data on KeyLessExchange: https://github.com/blankly-finance/blankly/blob/main/blankly/exchanges/interfaces/keyless/keyless_api.py#L58-L77

**Comment by bfan1256** [comment]
Hey @lomagno2003 , what are your thoughts on this approach? Would also love to get some feedback from the overall community too?
