### ISSUE TITLE
Support for UK/EU equities trading

### ISSUE THREAD

**Issue by 24dev** [blankly-finance/blankly#145]
## Description of Feature Request
- Support for an exchange that supports equities/stocks/etfs (etc) for UK/EU clients. Like Alpaca does for US based clients.

## Why is it important?
Currently it seems it's only possible to trade Crypto/Forex with Blankly if you're located outside the US.

## How would you use the feature?
N/A

## OPTIONAL: How would you implement this?
Connection to Interactive Brokers, maybe?

## Would you like to Contribute?

- [x] Yes, I would love to contribute to this feature request 🎉
- [ ] No, but please keep me posted 🎉

**Comment by EmersonDove** [comment]
Interactive brokers would be awesome, as I understand their API is a little complex to integrate with

**Comment by EmersonDove** [comment]
Merging with #184
