### ISSUE TITLE
error when using history with start/end dates 

### ISSUE THREAD

**Issue by pchalasani** [blankly-finance/blankly#166]
## Description
When I use start/end dates in the `state.interface.history( ... )` function, I get an error saying `an integer is required`.

## Code to reproduce

```python
exchange = blankly.CoinbasePro()

hist = exchange.interface.history(
    'ETH-USD',
    start_date='2021-04-25',
    end_date='2021-05-01',
    resolution='1d',
    return_as='deque'
)
```

## Error trace

```
    hist = exchange.interface.history('ETH-USD',
  File "/Users/pchalasani/Git/mlcrypt/.venv/lib/python3.8/site-packages/blankly/exchanges/interfaces/abc_base_exchange_interface.py", line 98, in history
    return self.cast_type(response, return_as, point_count)
  File "/Users/pchalasani/Git/mlcrypt/.venv/lib/python3.8/site-packages/blankly/exchanges/interfaces/abc_base_exchange_interface.py", line 161, in cast_type
    response[i] = deque(response[i], point_count)
TypeError: an integer is required
```

## Source of error

Stepping thru the debugger in PyCharm shows where the error is coming from, see this screenshot. Seems like `point_count` needs to be cast to an integer before the return statement.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/554347/166125846-7e5a4d24-1c60-44c4-b7df-de457520fa5a.png">

**Comment by EmersonDove** [comment]
Should be resolved on development, we will push this fix live when 1.18 is out.
