### ISSUE TITLE
cache the history data

### ISSUE THREAD

**Issue by jandykwan** [blankly-finance/blankly#182]
## Description of Feature Request
when backtest a strategy firstly, data should cache locally, so it won't fetch the data from exchange next time with the same time period and symbol

## Why is it important?
when develop a strategy, we will test again and again, so cache data will be great. 

## Would you like to Contribute?

- [X ] Yes, I would love to contribute to this feature request 🎉
- [ ] No, but please keep me posted 🎉

**Comment by EmersonDove** [comment]
Hey this should be entirely implemented. Make sure you have `"continuous_caching": true` in your `backtest.json`

**Comment by jandykwan** [comment]
such a great project !!! 🎉🎉🎉
