### ISSUE TITLE
On Alpaca, bar_event fires before the bar data is updated

### ISSUE THREAD

**Issue by efreed** [blankly-finance/blankly#189]
## Description
In testing my custom indicator compared to 3rd party chart, the blankly (w/alpaca) data seemed 1 minute behind.  It seems bar_event is called based on the clock, not based on when alpaca has new data?

Below I have an isolated bot.py and it's output.

Here's how I'm seeing it:
at 02:32:30 - the last history bar is 02:31 - makes sense, it's the last completed minute
For 30 seconds, the 1s bar_event gets the last completed minute bar.  - ok, guess there's no second bars :-)
at 02:33:00 - the bar_event fires, but does not give me 02:32 (the just completed minute), it gives me minute-old info (the 02:31 bar again)
If I sleep for 1-3 seconds and request the last minute from history then at 02:33:02 I can get the 02:32 bar.

Do I need to configure something differently?

## settings.json
```json
{
    "settings": {
        "use_sandbox_websockets": false,
        "websocket_buffer_size": 10000,
        "test_connectivity_on_auth": true,
        "coinbase_pro": {
            "cash": "USD"
        },
        "binance": {
            "cash": "USDT",
            "binance_tld": "com"
        },
        "alpaca": {
            "websocket_stream": "iex",
            "cash": "USD",
            "enable_shorting": true,
            "use_yfinance": false
        },
        "oanda": {
            "cash": "USD"
        },
        "keyless": {
            "cash": "USD"
        },
        "ftx": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "ftx_futures": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "kucoin": {
            "cash": "USDT"
        }
    }
}
```

## backtest.json --But not applicable, as this is an issue with running live
```json
{
    "price_data": {
        "assets": []
    },
    "settings": {
        "use_price": "close",
        "smooth_prices": false,
        "GUI_output": false,
        "show_tickers_with_zero_delta": false,
        "save_initial_account_value": true,
        "show_progress_during_backtest": false,
        "cache_location": "./price_caches",
        "continuous_caching": true,
        "resample_account_value_for_metrics": "1d",
        "quote_account_value_in": "USD",
        "ignore_user_exceptions": true,
        "risk_free_return_rate": 0.0,
        "benchmark_symbol": null
    }
}
```

## Error (if applicable)
```text
N/A
```

## Platform Info
 - Python version: 3.9.9
 - Platform: Mac OS (intel)

**Additional context**
Bot.py:
```python
import blankly
import time

def bar_event(bar, symbol, state: blankly.StrategyState):
    print('bar data given in 1m bar_event:')
    print(bar)
    time.sleep(2)
    history = state.interface.history(symbol, 1, state.resolution)
    print('last history bar 2 seconds after 1m bar_event: ')
    print(history)

def init(symbol, state: blankly.StrategyState):
    history = state.interface.history(symbol, 1, state.resolution)
    print('last history bar during init: ')
    print(history)

def second_bar_event(bar, symbol, state: blankly.StrategyState):
    print('time during second_bar_event: ' + str(round(bar['time'])))

exchange = blankly.Alpaca()
strategy = blankly.Strategy(exchange)
strategy.add_bar_event(bar_event, symbol='MSFT', resolution='1m', init=init)
strategy.add_bar_event(second_bar_event, symbol='MSFT', resolution='1s')
strategy.start()
```

Sample output:
```console
last history bar during init: 
         time    open    high     low    close   volume
0  1659465060  274.79  275.04  274.77  274.995  45749.0
time during second_bar_event: 1659465060
time during second_bar_event: 1659465060
...
time during second_bar_event: 1659465060
time during second_bar_event: 1659465060
bar data given in 1m bar_event:
{'time': 1659465060.0, 'open': 274.79, 'high': 275.04, 'low': 274.77, 'close': 274.995, 'volume': 45749.0}
time during second_bar_event: 1659465120
time during second_bar_event: 1659465120
last history bar 2 seconds after 1m bar_event: 
         time    open     high       low     close   volume
0  1659465120  275.02  275.129  274.9263  275.0799  22861.0
time during second_bar_event: 1659465120
time during second_bar_event: 1659465120
```

**Comment by EmersonDove** [comment]
Having trouble testing this because I don't have the advanced subscription to get data released in the last 15 minutes. However, I believe this was because we were querying alpaca the instant the bar finished. On exchanges like Coinbase or Binance, it takes a few seconds before the bar is added. For the crypto exchanges we just query over and over until we get the correct solution bar but Alpaca is a bit more difficult because of the market hours. 

I just added a small delay in there to match our other exchanges.

**Comment by efreed** [comment]
Thanks for looking at it.

Huh.  So when it's a stock market, it needs to support returning an old bar so the bar event can fire all night, all with the last bar of the day? 

It would be nice if it had the same wait-and-validate as crypto (but if I really need that, I can do it using a 1s bar event)  It's 58 seconds faster now, so seems a generally improved!

**Comment by EmersonDove** [comment]
I definitely agree it would be nice to wait and validate. You might want to directly connect to our websockets: https://docs.blankly.finance/websockets/websocket_manager if you're looking at a <1s resolution so that you can get updates every time a trade occurs.
