### ISSUE TITLE
blankly core code integrate too many real exchange code

### ISSUE THREAD

**Issue by jandykwan** [blankly-finance/blankly#192]
checking the source code, I found the blankly core code like TickManager and OrderbookManager integrate too many real exchange code like binance. I think the core code should implement a abstract exchange. any real exchange extend the abstract exchange inpedently. so we can add more exchagne easily.

**Comment by EmersonDove** [comment]
Hey,

Most of our code inherits from our base exchange found here:

https://github.com/blankly-finance/blankly/blob/cee3115588414862d2bf8020e99c188d13c4aebf/blankly/exchanges/interfaces/abc_exchange_interface.py#L31

Can you give an example of what needs refactoring?

**Comment by jandykwan** [comment]
in my opinion, in the core code like TickManager and OrderbookManager, these code should deal with the abstract exchange, no any binance or other exchnge code here.

**Comment by EmersonDove** [comment]
I'm not sure combining async `wss://` and sync `https://` schemes would offer any benefit especially when they have very different authentication methods. If you have an example of how there would be a benefit I would be happy to take a look!

**Comment by jandykwan** [comment]
take the TickManager for an example, the class is the core function of the framework.
in the fuction create_ticker of TickManager, the target of the fuction is to create a ticker,  many if else here, bysides, if more exchange added, more if else.  so if the TickManager holds an abstractr exchange, when call the create_ticker , will call the abstract  exchange var ( in fact , it's a real exchange instance).

**Comment by EmersonDove** [comment]
We do take advantage of this architecture here:

https://github.com/blankly-finance/blankly/blob/1260a9d4014be3d242c0b814be2ecdd23a039f5a/blankly/exchanges/abc_exchange_websocket.py#L22-L60

**Comment by jandykwan** [comment]
maybe my weak expression, you don't understand what I mean!

**Comment by EmersonDove** [comment]
I agree that the managers need work. Those were created when blankly was still a cross exchange arbitrage bot so they filled that original purpose well. The current package could definitely use some refactoring.
