### ISSUE TITLE
blankly init not working in Windows

### ISSUE THREAD

**Issue by pedroCabraAcela** [blankly-finance/blankly#193]
## Description
blankly init is not working for me on my Windows computer. I think is something related to the colors when printing, but I couldn't find exactly what.

## settings.json
```json
not yet created
```

## backtest.json (if applicable)
```json
not yet created
```

## Error (if applicable)
```text
prompt_toolkit.output.win32.NoConsoleScreenBufferError: Found xterm-color, while expecting a Windows console. Maybe try to run this program using "winpty" or run it in cmd.exe instead. Or otherwise, in case of Cygwin, use the Python executable that is compiled for Cygwin.
```

## Platform Info
 - Python version: Python 3.8.5
 - Platform: Spyder 4.2.5

**Additional context**

**Comment by EmersonDove** [comment]
Looks like thats the case in Spyder, try running it in `cmd` on windows. That platform has been well tested and should be supported.

**Comment by qmatias** [comment]
Sorry about that @pedroCabraAcela 
Can you try using Winpty? It allows software that expects a Windows console to run in this kind of terminal. Try the following `winpty blankly init`
