### ISSUE TITLE
Stock Split Adjustment with Alpaca

### ISSUE THREAD

**Issue by felixlaumon** [blankly-finance/blankly#195]
## Description
In https://github.com/blankly-finance/blankly/blob/main/blankly/exchanges/interfaces/alpaca/alpaca_interface.py#L398, `adjustment` is set to `raw` instead of `all` which leads to unexpected drop or increase in portfolio value. Is there a reason why it is set to `raw`?

## settings.json
```json
{
  "settings": {
    "use_sandbox_websockets": false,
    "websocket_buffer_size": 10000,
    "test_connectivity_on_auth": true,
    "auto_truncate": false,
    "global_shorting": false,
    "coinbase_pro": {
      "cash": "USD"
    },
    "binance": {
      "cash": "USDT",
      "binance_tld": "com"
    },
    "binance_futures": {
      "cash": "USDT",
      "margin_type": "USDT-M"
    },
    "alpaca": {
      "websocket_stream": "iex",
      "cash": "USD",
      "enable_shorting": true,
      "use_yfinance": false
    },
    "oanda": {
      "cash": "USD"
    },
    "okx": {
      "cash": "USDT"
    },
    "keyless": {
      "cash": "USD"
    },
    "kucoin": {
      "cash": "USDT"
    },
    "ftx": {
      "cash": "USD",
      "ftx_tld": "com"
    },
    "ftx_futures": {
      "cash": "USD",
      "ftx_tld": "com"
    },
    "paper": {
      "price_source": "api"
    }
  }
}
```

## backtest.json (if applicable)
```json
{
    "price_data": {
        "assets": []
    },
    "settings": {
        "use_price": "close",
        "smooth_prices": false,
        "GUI_output": true,
        "show_tickers_with_zero_delta": false,
        "save_initial_account_value": true,
        "show_progress_during_backtest": true,
        "cache_location": "./price_caches",
        "continuous_caching": true,
        "resample_account_value_for_metrics": "1d",
        "quote_account_value_in": "USD",
        "ignore_user_exceptions": true,
        "risk_free_return_rate": 0.0,
        "benchmark_symbol": null
    }
}
```

## Error (if applicable)
```text
Error here
```

## Platform Info
 - Python version: 3.8.13
 - Platform: 5.15.55-1-MANJARO

**Additional context**

**Comment by EmersonDove** [comment]
Hey Felix, when we did this integration which was a little over a year ago, the alpaca free plan didn't have access to split adjusted data. I believe that that point we didn't have a check if the account is premium/nonpremium so it has stayed in that state.

Things may have changed and that may need updating. Definitely let me know if you see a better way to approach that.

**Comment by felixlaumon** [comment]
I changed adjustment to all and it seems to work with my backtesting. I am on the free plan. Should I make a PR?

**Comment by EmersonDove** [comment]
Sure that would be great, if you make a PR I'll add a setting for it for anyone who does want to use non split adjusted data

**Comment by EmersonDove** [comment]
Hey have you had a chance to PR this? If not I will go ahead and close this.

**Comment by felixlaumon** [comment]
Sorry I won't be able to.
