### ISSUE TITLE
Integration of finvasia

### ISSUE THREAD

**Issue by bibinvargheset** [blankly-finance/blankly#196]
Finvasia is an great discount broker from india, can you integrate this?
is there a sample templete for intergration with expected input and outputs for the broker integration.?
https://github.com/Shoonya-Dev/ShoonyaApi-py

**Comment by EmersonDove** [comment]
Hey we don't have a guide yet for custom integrations but you can follow the format of two files like this:

https://github.com/blankly-finance/blankly/blob/main/blankly/exchanges/interfaces/alpaca/alpaca.py
https://github.com/blankly-finance/blankly/blob/main/blankly/exchanges/interfaces/alpaca/alpaca_interface.py

The `ExchangeInterface` object that the interface inherits from goes a good job defining the return types.
