### ISSUE TITLE
KeylessExchange yields wrong backtest results

### ISSUE THREAD

**Issue by Fschoeller** [blankly-finance/blankly#197]
Hi!
I wanted to test the KeylessExchange with a simple buy and hold on SPY.
It seems like the state does not register the account value while holding. I get backtest result of -98% cumulative return.

Here is a plot of account value as a function of time, where you can see that the value starts at 10000 USD but goes to 0 once i buy.
![image](https://user-images.githubusercontent.com/50424441/187415869-df4a9e93-77de-4501-919a-2b3595703f92.png)

**Comment by EmersonDove** [comment]
Hey are you running this on Alpaca? I would guess the data just got downloaded with some datapoint as zero which zeroed the account values. 

It could also be if you place a limit order when you buy you're selling for a very low price which will also zero your account.

**Comment by Fschoeller** [comment]
No this is keyless. The data is from yfinance. I use no limit orders, just buy and hold.
Here is a screenshot of the data showing no zero values.
![image](https://user-images.githubusercontent.com/50424441/187452360-b0defedf-1156-4e70-aafc-e6a50421d18d.png)

**Comment by Fschoeller** [comment]
Just tried your keyless example, same happens there.

**Comment by EmersonDove** [comment]
Interesting, this script:

https://github.com/blankly-finance/blankly/blob/main/examples/keyless_backtest.py

Works correctly for me without modification, maybe the one given when running `blankly init` isn't correct?

**Comment by Fschoeller** [comment]
And here is the backtest for my own strategy with keyless:
https://blankly.finance/links/oSkR22TN1njDN7Pu7

**Comment by EmersonDove** [comment]
Are you running with the newest version of blankly / can you run using the exact script I linked above. This would be the first instance of a Keyless backtest example being nondeterministic that I'm aware of.

**Comment by Fschoeller** [comment]
Yes, newest version. When I run the script you linked I get the output described in this [comment](https://github.com/blankly-finance/blankly/issues/197#issuecomment-1234453114):

**Comment by EmersonDove** [comment]
The difference between this script:
https://github.com/blankly-finance/blankly/blob/main/examples/keyless_backtest.py

And the initialized example are slightly different, can you make sure you're running that particular file.
