### ISSUE TITLE
No argument "resolution" as mentioned in docs

### ISSUE THREAD

**Issue by martinandrovich** [blankly-finance/blankly#200]
I am not sure if this is intentional, but the [`Screener` arguments documentation](https://docs.blankly.finance/core/screener/#arguments) mentions a `resolution` parameter which is not present in the code:

https://github.com/blankly-finance/blankly/blob/c326a3270f4d954c0c8dc9ce31ff411545176a5b/blankly/frameworks/screener/screener.py#L30-L36

**Comment by EmersonDove** [comment]
Ah you're right - we ported the timing to `blankly.json` and must have forgotten to update the docs.
