### ISSUE TITLE
screener created by blankly init hangs

### ISSUE THREAD

**Issue by nirno** [blankly-finance/blankly#202]
## Description

I run `blankly init -n`, select `Coinbase Pro`, select `Screener`, select `rsi_screener`, and add my keys.  Then I run `python bot.py`, and after saying 'These are all the stocks that are currently oversold:', the program hangs.

When running under `strace`, the last lines are:

    [pid 20139] write(1, "These are all the stocks that ar"..., 55) = 55
    [pid 20139] write(1, "\n", 1)           = 1
    [pid 20139] futex(0x7f3e9c000b70, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY

When I run `bot.py` in PyCharm, it exits normally.

## settings.json
```json
{
    "settings": {
        "use_sandbox_websockets": false,
        "websocket_buffer_size": 10000,
        "test_connectivity_on_auth": true,
        "auto_truncate": false,
        "global_shorting": false,
        "coinbase_pro": {
            "cash": "USD"
        },
        "binance": {
            "cash": "USDT",
            "binance_tld": "com"
        },
        "binance_futures": {
            "cash": "USDT",
            "margin_type": "USDT-M"
        },
        "alpaca": {
            "websocket_stream": "iex",
            "cash": "USD",
            "enable_shorting": true,
            "use_yfinance": false
        },
        "oanda": {
            "cash": "USD"
        },
        "okx": {
            "cash": "USDT"
        },
        "keyless": {
            "cash": "USD"
        },
        "kucoin": {
            "cash": "USDT"
        },
        "ftx": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "ftx_futures": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "paper": {
            "price_source": "api"
        }
    }
```

## backtest.json
```json
{
    "price_data": {
        "assets": []
    },
    "settings": {
        "use_price": "close",
        "smooth_prices": false,
        "GUI_output": true,
        "show_tickers_with_zero_delta": false,
        "save_initial_account_value": true,
        "show_progress_during_backtest": true,
        "cache_location": "./price_caches",
        "continuous_caching": true,
        "resample_account_value_for_metrics": "1d",
        "quote_account_value_in": "USD",
        "ignore_user_exceptions": true,
        "risk_free_return_rate": 0.0,
        "benchmark_symbol": null
    }
```

## Platform Info
 - Python version: 3.10.7
 - Platform: Arch Linux (last updated 2022-09-11)

**Additional context**
After interrupting the hanged program, Python outputs:
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by EmersonDove** [comment]
Hey this is expected behavior in the screener class. It's following the chron job settings in your `blankly.json`. It looks a bit confusing I think because there aren't any stocks currently oversold and then it starts sleeping waiting for the next run.
