### ISSUE TITLE
FTX PERP symbol

### ISSUE THREAD

**Issue by SamsTheGreatest** [blankly-finance/blankly#206]
Trying to add BTC-PERP on FTX it seems like it's trying to search for BTC/PERP on FTX and it obviously does not exist, so its untradable on blankly: `Exception: No such market: BTC/PERP `.

You guys created a very cool framework! Keep going!

**Comment by qmatias** [comment]
sorry for the confusion. the symbol name in blankly is still BTC-USD (yes, for perpetual futures).

this should be a better error message.
