### ISSUE TITLE
FTS future Buy

### ISSUE THREAD

**Issue by liuqiba** [blankly-finance/blankly#213]
## Description
Hello, first of all thank you very much for this library. Feels very good!

Unfortunately I get the following bug when using FTXFutures

You must using wrong Separator in ftx futrues.  ftx futrue Separator is "-"  and thers is "/",I had debug and found this.

this is my code
strategy.add_price_event(price_event, symbol='BTC-PREP', resolution='1d', init=init)
## settings.json
{
    "settings": {
        "use_sandbox_websockets": false,
        "websocket_buffer_size": 10000,
        "test_connectivity_on_auth": true,
        "auto_truncate": false,
        "global_shorting": false,
        "simulate_margin": true,
        "coinbase_pro": {
            "cash": "USD"
        },
        "binance": {
            "cash": "USDT",
            "binance_tld": "com"
        },
        "binance_futures": {
            "cash": "USDT",
            "margin_type": "USDT-M"
        },
        "alpaca": {
            "websocket_stream": "iex",
            "cash": "USD",
            "enable_shorting": true,
            "use_yfinance": false
        },
        "oanda": {
            "cash": "USD"
        },
        "okx": {
            "cash": "USDT"
        },
        "keyless": {
            "cash": "USD"
        },
        "kucoin": {
            "cash": "USDT"
        },
        "ftx": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "ftx_futures": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "paper": {
            "price_source": "api"
        }
    }
}
settings.json here
```

## backtest.json (if applicable)
{
    "price_data": {
        "assets": []
    },
    "settings": {
        "use_price": "close",
        "smooth_prices": false,
        "GUI_output": true,
        "show_tickers_with_zero_delta": false,
        "save_initial_account_value": true,
        "show_progress_during_backtest": true,
        "cache_location": "./price_caches",
        "continuous_caching": true,
        "resample_account_value_for_metrics": "1d",
        "quote_account_value_in": "USD",
        "ignore_user_exceptions": true,
        "risk_free_return_rate": 0.0,
        "benchmark_symbol": null
    }
}
```

## Error (if applicable)
C:\Python310\python.exe C:/Users/Nothing/PycharmProjects/BlanklyTest/Future.py
INFO: No portfolio name to load specified, defaulting to the first in the file: (ftxT). This is fine if there is only one portfolio in use.
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtesting_wrapper.py", line 52, in get_backtesting_price
    return self.frame['prices'][asset_id]
KeyError: 'BTC-USD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 651, in format_account_data
    price = interface.get_price(currency_pair)
  File "C:\Python310\lib\site-packages\blankly\exchanges\interfaces\paper_trade\paper_trade_interface.py", line 752, in get_price
    return self.get_backtesting_price(symbol)
  File "C:\Python310\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtesting_wrapper.py", line 54, in get_backtesting_price
    raise KeyError(f"Price not found in recent frame. Have prices for {asset_id} been downloaded?")
KeyError: 'Price not found in recent frame. Have prices for BTC-USD been downloaded?'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nothing\PycharmProjects\BlanklyTest\Future.py", line 50, in <module>
    results = strategy.backtest(to='1y', initial_values={'USD': 10000})
  File "C:\Python310\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 320, in backtest
    res = self.model.backtest(args={}, initial_values=initial_values, settings_path=settings_path, kwargs=kwargs)
  File "C:\Python310\lib\site-packages\blankly\frameworks\model\model.py", line 64, in backtest
    backtest = self.__backtester.run(args,
  File "C:\Python310\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 930, in run
    available_dict, no_trade_dict = self.format_account_data(self.interface, self.user_start)
  File "C:\Python310\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 655, in format_account_data
    raise KeyError(f"Failed to quote {currency_pair} because no downloaded data for that pair is available. "
KeyError: 'Failed to quote BTC-USD because no downloaded data for that pair is available. Make sure to set "quote_account_value_in" in "backtest.json" to match the prices you are using. For example if you are trading "USD-JPY", set your quote value to "JPY". Currently it is set to USD'

Process finished with exit code 1

```

## Platform Info
 - Python version:310
 - Platform:win10

**Additional context**
all code :
import  blankly
from blankly import futures
from blankly.futures import FuturesStrategyState
from blankly.futures.utils import close_position

def price_event(price, symbol, state: blankly.futures.FuturesStrategyState):
    """ This function will give an updated price every 15 seconds from our definition below """
    state.variables.history.append(price)

    rsi = blankly.indicators.rsi(state.variables.history)
    current_position = state.interface.get_position(symbol)

    if rsi[-1] < 30 and not current_position:
        # Dollar cost average buy
        buy = blankly.trunc(state.interface.cash / price, state.variables.precision)
        state.interface.market_order(symbol, side='buy', size=buy)

    elif rsi[-1] > 70 and current_position:
        # Sell our position
        state.interface.market_order(symbol, side='sell', size=current_position)


def init(symbol, state: blankly.StrategyState):
    # Download price data to give context to the algo
    state.variables.history = state.interface.history(symbol, to=150, return_as='deque',
                                                      resolution=state.resolution)['close']

    # Get the max precision for this symbol from the API
    increment = next(product['base_increment']
                     for product in state.interface.get_products()
                     if product['symbol'] == symbol)
    state.variables.precision = blankly.utils.increment_to_precision(increment)


if __name__ == "__main__":
    # Authenticate FTX strategy

    exchange = blankly.FTX()

    # Use our strategy helper on FTX
    strategy = futures.FuturesStrategy(exchange)

    # Run the price event function every time we check for a new price - by default that is 15 seconds
    strategy.add_price_event(price_event, symbol='BTC-PERP', resolution='1d', init=init)

    # Start our strategy, or run a backtest if this script is run locally.
    if blankly.is_deployed:
        strategy.start()
    else:
        results = strategy.backtest(to='1y', initial_values={'USD': 10000})
        print(results)

**Comment by EmersonDove** [comment]
Hey can you give any more details about the error that you're seeing

**Comment by liuqiba** [comment]
I found this in ftx_interface.py:
    def ftx_product_history(api, symbol, epoch_start, epoch_stop, resolution):
        # TODO this is probably the wrong place to put this code
        # shared binance history code needs to be refactored as well
        symbol = symbol.replace("-", "/")

**Comment by liuqiba** [comment]
Remove this line "symbol = symbol.replace("-", "/")" maybe

**Comment by liuqiba** [comment]
And your ftx future history request is wrong ,thers is "https://ftx.com/api/markets/{market_name}/candles"
The correct one should be:
https://ftx.com/api/indexes/{index_name}/candles

**Comment by EmersonDove** [comment]
Hey sorry for the late response, we use the `-` format universally in the package and then convert when the exchange requires it, the examples should be correct with `BTC-PERP`. This is sort of a moot point though with the FTX bankruptcy.

**Comment by EmersonDove** [comment]
Closing because FTX is gone.
