### ISSUE TITLE
get file extension using pathlib

### ISSUE THREAD

**Issue by femtotrader** [blankly-finance/blankly#226]
https://github.com/blankly-finance/blankly/blob/41f5294d3bad3937a887355530afb450df87de85/blankly/data/data_reader.py#L269

is not a very "clean" way of getting file extension.

maybe you should consider using pathlib

https://docs.python.org/3/library/pathlib.html and `.suffixes` attribute

an older way of doing may be to use `os.path.splitext`

**Comment by EmersonDove** [comment]
Oh yeah probably would be better - happy to accept a contribution.

cleaning up the exception would also be nice to do something like `assert <condition>, "The file path did not have a csv ending...`
