### ISSUE TITLE
Backtest results as pickle save or an other serialization format

### ISSUE THREAD

**Issue by femtotrader** [blankly-finance/blankly#227]
Hello,

when running a very long backtest it could be interesting to have "out of the box" a save (maybe a [pickle object](https://docs.python.org/3/library/pickle.html)) of backtest results so it could be possible to watch backtest results but also watch any others actions what was performed during backtest (orders especially).
This kind of mechanism is used by other backtester such a zipline.

Kind regards

PS : other serialization format could also be considered (cPickle, JSON, BSON, HDF5, Feather, Parquet, Jay...)

**Comment by EmersonDove** [comment]
I"m not sure it should be default behavior but i could see better support for a pickle

**Comment by femtotrader** [comment]
An interesting use case could be to run a strategy compared to an other one (for example a strategy compared to buy and hold strategy).
So we could draw a relative account plot in % (relative account plot, account plot relative to reference strategy)

**Comment by EmersonDove** [comment]
Oh i agree with that. Originally the platform had this functionality, hopefully that can be self-hosted soon!
