### ISSUE TITLE
Add custom plot

### ISSUE THREAD

**Issue by femtotrader** [blankly-finance/blankly#228]
Hello,

it could be nice to have an option to add custom plot to Bokeh plot (below account value).

    plot_line("buy rsi zone", signal_params[BUY_RSI])

could add a simple plot

    with Plot.group("rsi"):
        plot_line("buy rsi zone", signal_params[BUY_RSI])
        plot_line("sell rsi zone", signal_params[SELL_RSI])
        plot_line("rsi", rsi2)

could add 3 plots in a subplot.

Kind regards

**Comment by EmersonDove** [comment]
You can grab the plots from the `BacktestResult` object, add data to it and then re-plot that information, we just generate an initial plot but it is totally modular :).
