### ISSUE TITLE
Cannot run blankly login

### ISSUE THREAD

**Issue by kintonc** [blankly-finance/blankly#235]
## Description
I am using Blankly for the first time and following the [Your first algorithm](https://docs.blankly.finance/getting-started/your-first-algorithm/) guide. It says I can run `blankly login` command to link to Blankly Slate. 

However, `blankly login` returns:
```
usage: blankly [-h] {init,key} ...
blankly: error: argument {init,key}: invalid choice: 'login' (choose from 'init', 'key')
```

Also, I don't see any way to sign up for Blankly Slate anymore (on the [site[(https://docs.blankly.finance/getting-started/your-first-algorithm/#linking-with-blankly-slate-platform), it says there's a free plan to sign up for).

## settings.json
```json
{
    "settings": {
        "use_sandbox_websockets": false,
        "websocket_buffer_size": 10000,
        "test_connectivity_on_auth": true,
        "auto_truncate": false,
        "global_shorting": false,
        "simulate_margin": true,
        "coinbase_pro": {
            "cash": "USD"
        },
        "binance": {
            "cash": "USDT",
            "binance_tld": "com"
        },
        "binance_futures": {
            "cash": "USDT",
            "margin_type": "USDT-M"
        },
        "alpaca": {
            "websocket_stream": "iex",
            "cash": "USD",
            "enable_shorting": true,
            "use_yfinance": false
        },
        "oanda": {
            "cash": "USD"
        },
        "okx": {
            "cash": "USDT"
        },
        "keyless": {
            "cash": "USD"
        },
        "kucoin": {
            "cash": "USDT"
        },
        "ftx": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "ftx_futures": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "paper": {
            "price_source": "api"
        }
    }
}
```

## backtest.json (if applicable)
N/A

## Error (if applicable)
See above

## Platform Info
 - Python version: 3.9
 - Platform: 1.18.24b0

**Additional context**
N/A

**Comment by EmersonDove** [comment]
Hey @kintonc, this is expected behavior due to us removing login functionality when we open sourced the blankly platform for self-hosting.

Sorry about the guide, I'll add that fix to remove that to our project board.

**Comment by kintonc** [comment]
Thanks for the quick reply! Is there any self-hosted version of Blankly Platform available?

**Comment by EmersonDove** [comment]
Yes - we open sourced it just a few weeks ago: https://github.com/blankly-finance/blankly-os

**Comment by zaleGZL** [comment]
> Yes - we open sourced it just a few weeks ago: https://github.com/blankly-finance/blankly-os

@EmersonDove  hi, EmersonDove, Is it convenient to share what is the highest MRR of this product? How many monthly subscribers are there?

**Comment by EmersonDove** [comment]
> > Yes - we open sourced it just a few weeks ago: https://github.com/blankly-finance/blankly-os
> 
> @EmersonDove hi, EmersonDove, Is it convenient to share what is the highest MRR of this product? How many monthly subscribers are there?

I would rather not, but it was low though - primarily because we didn't require payment for anything but collaboration - but I do think a second party hosted version of this could easily make $1k+ MRR rather quickly.

**Comment by zaleGZL** [comment]
Okay, thank you EmersonDove, and wish your new company Shade better and better~
