### ISSUE TITLE
How do backtests account for fees when projecting growth?

### ISSUE THREAD

**Issue by Nomenator** [Blankly-Finance/Blankly#70]
It would make no sense to keep selling and buying an instrument if price fluctuations are smaller than the trading fees. Do backtests use the functionality built into `MarketOrder` and `LimitOrder`? Do we need to explicitly implement fee impact analysis in our price events?

**Comment by EmersonDove** [comment]
Great question!

The fees are copied accurately from the exchange and then used when evaluating your orders:
https://github.com/Blankly-Finance/Blankly/blob/5ee6f0f09bbe4d7ecfb5efa0704ce7f01a6a5a44/blankly/exchanges/interfaces/paper_trade/paper_trade_interface.py#L385-L405

No need to account for fees in your code!

**Comment by Nomenator** [comment]
Fantastic, thank you.
