### ISSUE TITLE
Backtest crashing depending on time-frame

### ISSUE THREAD

**Issue by wine** [Blankly-Finance/Blankly#71]
## Description
Running a backtest of 1 month with 60 seconds resolution `strategy.backtest(to="1M", ...)` on Binance XRP-USDT pair crashes when calculating RSI.
24h, 48h and 96h works fine but going up to 168h/1w causes same crash.

## Error (if applicable)
```python
  File "F:\Trunk\wine\blankly-test\models\RelativeStrengthIndexDecisionModel.py", line 16, in __call__
    rsi = blankly.indicators.rsi(state.variables["history"], self.period)
  File "C:\Users\ian\AppData\Local\Programs\Python\Python39\lib\site-packages\blankly\indicators\oscillators.py", line 33, in rsi
    rsi_values = ti.rsi(data, period)
  File "C:\Users\ian\AppData\Local\Programs\Python\Python39\lib\site-packages\tulipy\__init__.py", line 1003, in rsi
    return lib.rsi([real], [period])
  File "tulipy\lib\__init__.pyx", line 105, in tulipy.lib._Indicator.__call__
tulipy.lib.InvalidOptionError
```

## Platform Info
 - Python version: 3.9.7 x86-64
 - Platform: Windows 10

**Comment by EmersonDove** [comment]
Interesting, this could be because you're running on the binance sandbox exchange. Binance deletes all sandbox history data at the first of every month. When calculating RSI the algo needs a certain number of points to run the calculation - it could be throwing an error because it doesn't have enough data.

I recommend creating or using live keys so you can get really old data - you can turn trade permissions off in the setup and make them only data keys!

**Comment by EmersonDove** [comment]
I would recommend checking out #68 for an example of more people having issues with the binance sandbox data.

**Comment by wine** [comment]
> Interesting, this could be because you're running on the binance sandbox exchange. Binance deletes all sandbox history data at the first of every month. When calculating RSI the algo needs a certain number of points to run the calculation - it could be throwing an error because it doesn't have enough data.
> 
> I recommend creating or using live keys so you can get really old data - you can turn trade permissions off in the setup and make them only data keys!

Ah, I was not aware that Binance clears the sandbox every first of the month; just tested it on the real Binance and it works with 1 month etc. Thanks a lot for the explanation 👍
