### ISSUE TITLE
Shorting stock not developed?

### ISSUE THREAD

**Issue by bkunsberg** [blankly-finance/blankly#73]
Hi, 

Thank you for the very useful package!
I'm trying to backtest a strategy that involves shorting a stock/crypto. This means I make a call like:
interface.market_order('MSFT', 'sell', 1)
in a price_event function.

This results in an error message such as:
*** blankly.utils.exceptions.InvalidOrder: Not enough base currency. Available: 0.0. hold: 0. requested: 1.

I'd expect to be able to short on Alpaca, as doing a 'sell' market order (e.g. through their web console) with 0 position is successful.

Note: I've gotten the same results with 

    alpaca = Alpaca()
    s = Strategy(alpaca)

and
    coinbase = CoinbasePro()
    crypto = Strategy(coinbase)

Is this intentional?  Thanks so much!

**Comment by EmersonDove** [comment]
Yep you are absolutely right. We haven't implemented the shorting for alpaca in the backtesting framework - this is the most significant feature that we're missing in a full alpaca integration.

We are working on this, I will attach this issue to a pull.

**Comment by bkunsberg** [comment]
Thanks for the quick reply!  Looking forward to the full integration.

**Comment by sjhermanek** [comment]
@EmersonDove glad you're working on this! Do you plan to do the same for Crypto (e.g. binance API)?

**Comment by EmersonDove** [comment]
@sjhermanek This is a really good question. I suppose I'm not sure of the answer because I'm not really a binance user.

As I understand it, the margin API calls are through different endpoints which would make that integration significantly more complex but I'm not super sure. I think because of this we are going to wait for that more advanced stuff.

**Comment by EmersonDove** [comment]
This feature is now active on the dev branch.

**Comment by bfan1256** [comment]
@bkunsberg , this is now live! Let us know what you think 💭

**Comment by bkunsberg** [comment]
Thank you for adding this feature so fast!  I think it will be really
useful for me (and others).  Looking forward to trying it out.

**Comment by femtotrader** [comment]
Shorting on Binance and with KeylessExchange seems to also be impossible. Any idea if it will be possible in a next release ?

**Comment by EmersonDove** [comment]
The `blankly.Binance()` exchange is spot, so shorting is disabled. `KeylessExchange` is also made to mimic spot so I didn't add an option for shorting but I could see an argument for adding it.

**Comment by femtotrader** [comment]
Supporting Binance cross margin will be great also.
