### ISSUE TITLE
[Feature] Arbitrage Events within an Exchange

### ISSUE THREAD

**Issue by bfan1256** [blankly-finance/blankly#77]
## Description
One of the main use cases of trading models is for arbitrage events that rely on the simultaneous reading of two data streams. Say for example that you want to trade Coke (NYSE:KO) and Pepsi (NYSE:PEP), we want to be able to read from both and generate a synthetic price from each. 

## What would this look like? 

I would think that within a `Strategy` we could add an `add_arbitrage_event(event_handler, <ticker_1>, <ticker_2>, resolution)` that uses the same interface to get the price data simultaneously. 

## Full Use Case Example

```python
from blankly import Alpaca, Strategy

def mean_reversion(price_symbol_1, price_symbol_2, state):
    ratio = price_symbol_2 / price_symbol_1
    if ratio > 1:
        # do something 
    else:
        # do something else

a = Alpaca()
s = Strategy(a)
s.add_arbitrage_event(mean_reversion, 'MSFT', 'AAPL', '15m')
s.backtest(to='2y')
```

**Comment by sjhermanek** [comment]
I got this to run (after some hacking around) by adding two assets to the same `strategy` as such:
```
  # Add price events to strategy. This means that for every lapse of resolution, we will be calling the price_event function once, for each symbol (pair, secondary) defined.
  strategy.add_price_event(price_event, secondary, resolution=resolution)
  strategy.add_price_event(price_event, pair, resolution=resolution, init=init, teardown=teardown)
```

And then in `price_event`
```
if (symbol == pair):
    variables['history'].append(price)
    variables[secondary]['history'].append(interface.get_price(secondary))
else:
    return

... # Rest of your logic
```

There was a bit of fiddling around in the `init` - make sure to call it only once.
```
variables['history'] = interface.history(pair, 1200, resolution, end_date=state.time, return_as='deque')['close']
variables[secondary] = {}
variables[secondary]["history"] = interface.history(secondary, 1200, resolution, end_date=state.time, return_as='deque')['close']

... # Rest of your logic
```

(Make sure to set `secondary` to global context)
