### ISSUE TITLE
[suggestion] check python version in during install

### ISSUE THREAD

**Issue by aleeusgr** [blankly-finance/blankly#78]
I've been banging my head on a wall on why does backtesting show an error upon finishing:

    /blankly/exchanges/interfaces/paper_trade/backtest_controller.py
    AttributeError: 'Figure' object has no attribute 'step'

Upgrading to python 3.10.0 solved the issue, I was using 3.8.11.

Maybe this can be checked during installation for convnivence? 

Thank you

**Comment by EmersonDove** [comment]
Hmm that's really interesting. We use 3.7 to develop so I'm surprised that 3.10 works better than 3.8. I think I will change our unit tests to run a wide range of python versions to avoid errors like this!

**Comment by bfan1256** [comment]
This has now been fixed in our latest unit tests! @aleeusgr thanks for posting this? Are you in our [discord](https://discord.gg/xJAjGEAXNS) by chance?  Would love to chat!

**Comment by bidreshivaprasad** [comment]
i have an issue to installation ,

error: subprocess-exited-with-error

  × Building wheel for newtulipy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
im using Python 3.10.4

**Comment by EmersonDove** [comment]
We've definitely had a lot of issues with users building the newtulipy library on python 3.10. You can try using an older version of python 3.7 or later. We're working on distributing more wheels of tulipy.
