### ISSUE TITLE
Is there an OCO order in the framework?

### ISSUE THREAD

**Issue by hesihan1994** [Blankly-Finance/Blankly#81]
I want to implement OCO orders for Binance but it's not found in the document. Should I implement it manually? 

To build it manually, I plan to:
- Place 3 orders when my strategy decides to take a position. 
    - A market order for buy/long or sell/short. 
    - A limit order for stop loss. 
    - a stop limit order for take profit. 
- Monitor the status of the limit order and stop limit order. If one of them is achieved, cancel the other. 

Is there a better way to do this?

**Comment by EmersonDove** [comment]
This seems like the best approach. We don't currently have plans to create functions for these advanced order types but it largely depends on demand.

When going live, you can monitor order status extremely accurately by using a websocket for price/trade data. When an order is placed you can create the websocket connection and pass along the order IDs that were given when the trade was created. The websocket events can easily check if either should be canceled.

It does look like Binance may have changed something with their websocket so the integration may be down.
