### ISSUE TITLE
[Praise] Can't wait for Blankly Platform!

### ISSUE THREAD

**Issue by sjhermanek** [Blankly-Finance/Blankly#82]
Not a bug, not a feature request - just a quick note saying that I can't wait for Blankly Platform early access and wanted to applaud the entire team for their outstanding work! Keep it up!

**Comment by EmersonDove** [comment]
Super cool you're excited about it! We're coding it all up as we speak - if you're interested & you have a few projects to try out I can add you to the private beta which will be rolling out in a few weeks.

**Comment by sjhermanek** [comment]
I'd love that @EmersonDove . Is my understanding correct that I can deploy/automate execution through that (without having to worry about EC2 instances etc.)?

**Comment by EmersonDove** [comment]
Yep thats absolutely correct - there is also a suite of very detailed monitoring tools built in to show its behavior and actions/trades made. Another cool feature is that you can run backtests & analyze the results which helps show how you've improved your model over time.

**Comment by sjhermanek** [comment]
Amazing, can't wait! (I hope I can finally migrate away from my Google Colab notebook :D )

**Comment by bfan1256** [comment]
@sjhermanek how'd you like the demo? ;)

**Comment by sjhermanek** [comment]
@bfan1256 @EmersonDove It was amazing! It even inspired me to fix my local installation of Python ;)
