### ISSUE TITLE
Feature Request: Alpaca Stop Limit Orders

### ISSUE THREAD

**Issue by mitchweaver** [blankly-finance/blankly#91]
I see it's not currently supported, this would be a big boost. Very cumbersome to implement manually.

https://github.com/Blankly-Finance/Blankly/blob/95a63f8234fa3d6f8870aeea330d0c1ab4fb1fd6/blankly/exchanges/interfaces/alpaca/alpaca_interface.py#L153

Love the project!

**Comment by EmersonDove** [comment]
Glad you like it!

We've worked on and off on adding the stop support and also experienced a ton of demand - you can see a super secret implementation of it in the Coinbase Pro interface. It's in our pipeline, I think we would go for a full implementation across exchanges by late January.
